//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigPictureManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigPictureManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }

        internal static string MenuHeaderAudio {
            get {
                return ResourceManager.GetString("MenuHeaderAudio", resourceCulture);
            }
        }

        internal static string MenuHeaderOnBpStart {
            get {
                return ResourceManager.GetString("MenuHeaderOnBpStart", resourceCulture);
            }
        }

        internal static string MenuHeaderOnBpExit {
            get {
                return ResourceManager.GetString("MenuHeaderOnBpExit", resourceCulture);
            }
        }

        internal static string MenuHeaderApp {
            get {
                return ResourceManager.GetString("MenuHeaderApp", resourceCulture);
            }
        }

        internal static string MenuHeaderControllerService {
            get {
                return ResourceManager.GetString("MenuHeaderControllerService", resourceCulture);
            }
        }

        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }

        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }

        internal static string MenuInstallControllerService {
            get {
                return ResourceManager.GetString("MenuInstallControllerService", resourceCulture);
            }
        }

        internal static string MenuRemoveControllerService {
            get {
                return ResourceManager.GetString("MenuRemoveControllerService", resourceCulture);
            }
        }

        internal static string MenuAudioNoDevices {
            get {
                return ResourceManager.GetString("MenuAudioNoDevices", resourceCulture);
            }
        }
        
        internal static string MenuBluetoothNoDevice {
            get {
                return ResourceManager.GetString("MenuBluetoothNoDevice", resourceCulture);
            }
        }
        
        internal static string MenuBluetoothTurnOffOnBpClose {
            get {
                return ResourceManager.GetString("MenuBluetoothTurnOffOnBpClose", resourceCulture);
            }
        }
        
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        internal static string MenuLaunchOnStart {
            get {
                return ResourceManager.GetString("MenuLaunchOnStart", resourceCulture);
            }
        }
        
        internal static string MenuNightLightTurnOffOnBpStart {
            get {
                return ResourceManager.GetString("MenuNightLightTurnOffOnBpStart", resourceCulture);
            }
        }
        
        internal static string MenuPauseMedia {
            get {
                return ResourceManager.GetString("MenuPauseMedia", resourceCulture);
            }
        }
        
        internal static string MenuWirelessXboxController {
            get {
                return ResourceManager.GetString("MenuWirelessXboxController", resourceCulture);
            }
        }
        
        internal static string MsgAlreadyRunning {
            get {
                return ResourceManager.GetString("MsgAlreadyRunning", resourceCulture);
            }
        }

        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
    }
}
